import Lottie from 'lottie-react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import loadingAnimation from "../public/loader.json";
import { observer } from 'mobx-react-lite';
import { useStore } from '../data/mobx/store';
import { useEffect } from 'react';

const Home: NextPage = observer(() => {
  const { authStore } = useStore();
  const loggedIn = authStore.authState.loggedIn;
  const error = authStore.authState.error;


  useEffect(() => {
    authStore.isUserLoggedIn();
    if (loggedIn !== undefined) {
      if (loggedIn) {
        window.location.replace("/home");
      } else {
        window.location.replace("/login");
      }
    }
  }, [loggedIn]);
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css?family=Public+Sans"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Montserrat"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossOrigin='anonymous'
        />

      </Head>

      <main>
        <Lottie
          style={{
            width: "50%",
            left: "25%",
            position: "relative",
            height: "100vh",
            alignContent: "center"
          }}
          animationData={loadingAnimation}
        />
      </main>
    </div>
  )
});

export default Home
